import { Restaurant, MealPlan, Post } from './types';

export const posts: Post[] = [
  {
    id: 'p1',
    userId: 'u1',
    userName: '草莓芝士',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    restaurantId: '1',
    restaurantName: '学子居黄焖鸡',
    title: '这家黄焖鸡绝了！',
    content: '今天去了学子居，黄焖鸡软糯适中，汤汁浓郁。配上大白米饭，简直是人间美味。强烈推荐给各位同学！',
    images: ['https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?w=800&q=80'],
    rating: 5,
    orderedDishes: ['招牌黄焖鸡', '凉拌海带丝'],
    likes: 128,
    comments: [
      { id: 'c1', userId: 'u2', userName: '美食家小王', content: '确实，我也觉得这家黄焖鸡最好吃', createdAt: '2024-03-10' }
    ],
    createdAt: '2024-03-10'
  },
  {
    id: 'p2',
    userId: 'u2',
    userName: '健身达人',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
    restaurantId: '10',
    restaurantName: '绿野仙踪沙拉',
    title: '减脂期首选，沙拉分量很足',
    content: '最近在刷脂，这家沙拉店的鸡胸肉一点都不柴，配上油醋汁非常清爽。环境也很安静，适合一个人慢慢吃。',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80'],
    rating: 4.5,
    orderedDishes: ['经典凯撒沙拉', '牛油果奶昔'],
    likes: 85,
    comments: [],
    createdAt: '2024-03-12'
  },
  {
    id: 'p3',
    userId: 'u3',
    userName: '辣妹子',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    restaurantId: '2',
    restaurantName: '川香阁',
    title: '辣得过瘾！水煮鱼必点',
    content: '喜欢吃辣的同学千万不要错过！水煮鱼的鱼肉很嫩，麻辣味十足。就是排队的人有点多，建议早点去。',
    images: ['https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?w=800&q=80'],
    rating: 4.8,
    orderedDishes: ['水煮鱼', '麻婆豆腐'],
    likes: 210,
    comments: [
      { id: 'c2', userId: 'u4', userName: '不吃香菜', content: '这家店确实火，每次去都要排半天', createdAt: '2024-03-13' }
    ],
    createdAt: '2024-03-13'
  },
  {
    id: 'p4',
    userId: 'u4',
    userName: '甜品控',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver',
    restaurantId: '25',
    restaurantName: '法式甜品店',
    title: '未名湖畔的浪漫下午茶',
    content: '草莓慕斯酸甜适中，口感细腻。坐在湖边喝着红茶，感觉时间都慢下来了。虽然有点贵，但偶尔奢侈一下也很不错。',
    images: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80'],
    rating: 4.8,
    orderedDishes: ['草莓慕斯', '大吉岭红茶'],
    likes: 156,
    comments: [],
    createdAt: '2024-03-14'
  },
  {
    id: 'p5',
    userId: 'u5',
    userName: '面条爱好者',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jack',
    restaurantId: '19',
    restaurantName: '兰州拉面',
    title: '人大南门的兰州拉面，性价比之王',
    content: '15块钱一大碗，加面还免费！汤底很醇厚，辣子也很香。对于学生党来说，这就是最实在的美味。',
    images: ['https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=800&q=80'],
    rating: 4.2,
    orderedDishes: ['牛肉拉面'],
    likes: 92,
    comments: [],
    createdAt: '2024-03-14'
  },
  {
    id: 'p6',
    userId: 'u6',
    userName: '炸鸡达人',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Milo',
    restaurantId: '12',
    restaurantName: '韩式炸鸡店',
    title: '韩式炸鸡，宿舍追剧必备',
    content: '蜂蜜芥末味真的绝绝子！外皮酥脆，里面肉质多汁。配上冰镇可乐，简直是人间理想。',
    images: ['https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&q=80'],
    rating: 4.6,
    orderedDishes: ['蜂蜜芥末炸鸡', '冰镇可乐'],
    likes: 143,
    comments: [],
    createdAt: '2024-03-14'
  },
  {
    id: 'p7',
    userId: 'u7',
    userName: '日料小公举',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophie',
    restaurantId: '11',
    restaurantName: '精致日料',
    title: '精致日料，约会首选',
    content: '三文鱼刺身非常新鲜，厚切吃起来超级满足。鳗鱼饭也做得很地道。环境很有氛围，适合情侣约会。',
    images: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80'],
    rating: 4.7,
    orderedDishes: ['三文鱼刺身', '鳗鱼饭'],
    likes: 118,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p8',
    userId: 'u8',
    userName: '川菜发烧友',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leo',
    restaurantId: '1',
    restaurantName: '学子居黄焖鸡',
    title: '麻辣鲜香的川菜馆，够味！',
    content: '毛血旺配料丰富，辣味十足。麻婆豆腐也很下饭。喜欢吃辣的朋友千万不要错过。',
    images: ['https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?w=800&q=80'],
    rating: 4.5,
    orderedDishes: ['招牌黄焖鸡', '麻婆豆腐'],
    likes: 167,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p9',
    userId: 'u9',
    userName: '早茶爱好者',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia',
    restaurantId: '15',
    restaurantName: '港式茶餐厅',
    title: '港式茶餐厅，周末早起就为了这一口',
    content: '水晶虾饺皮薄馅大，奶茶丝滑。叉烧包也很好吃。很有老香港的感觉。',
    images: ['https://images.unsplash.com/photo-1583182332473-b31ba08929c8?w=800&q=80'],
    rating: 4.5,
    orderedDishes: ['水晶虾饺', '冰镇奶茶'],
    likes: 134,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p10',
    userId: 'u10',
    userName: '汉堡达人',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Toby',
    restaurantId: '2',
    restaurantName: '绿野轻食社',
    title: '美式汉堡，肉饼厚实多汁',
    content: '虽然是轻食社，但他们的汉堡真的太满足了。薯条也炸得恰到好处。偶尔放纵一下的最佳选择。',
    images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80'],
    rating: 4.4,
    orderedDishes: ['经典凯撒沙拉', '炸薯条'],
    likes: 112,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p11',
    userId: 'u11',
    userName: '披萨控',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Luna',
    restaurantId: '17',
    restaurantName: '意式披萨屋',
    title: '意式披萨，底薄边脆',
    content: '玛格丽特披萨最考验功力，这家做得非常地道。芝士拉丝很长。',
    images: ['https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80'],
    rating: 4.6,
    orderedDishes: ['玛格丽特披萨'],
    likes: 178,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p12',
    userId: 'u12',
    userName: '东南亚风情',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zoe',
    restaurantId: '3',
    restaurantName: '泰式料理',
    title: '泰式料理，酸辣开胃',
    content: '冬阴功汤味道很正，椰汁西米露也很甜。仿佛回到了曼谷街头。',
    images: ['https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80'],
    rating: 4.6,
    orderedDishes: ['冬阴功汤', '椰汁西米露'],
    likes: 145,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p13',
    userId: 'u13',
    userName: '健康达人',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Max',
    restaurantId: '4',
    restaurantName: '绿野轻食社',
    title: '轻食沙拉，健康又美味',
    content: '鸡胸肉沙拉分量很足，酱汁也有很多选择。是健身后的完美补给。',
    images: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80'],
    rating: 4.7,
    orderedDishes: ['鸡胸肉沙拉'],
    likes: 123,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p14',
    userId: 'u14',
    userName: '深夜食堂',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sam',
    restaurantId: '30',
    restaurantName: '深夜炸串',
    title: '深夜炸串，解馋神器',
    content: '万物皆可炸，深夜来几串，所有的压力都消失了。',
    images: ['https://images.unsplash.com/photo-1562607378-27b1bd99326c?w=800&q=80'],
    rating: 4.3,
    orderedDishes: ['炸鸡柳', '炸薯条'],
    likes: 567,
    comments: [],
    createdAt: '2024-03-15'
  },
  {
    id: 'p15',
    userId: 'u15',
    userName: '湘菜爱好者',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava',
    restaurantId: '29',
    restaurantName: '精品湘菜',
    title: '剁椒鱼头，辣得过瘾',
    content: '鱼头很大，剁椒很香。拌上面条简直是绝配。',
    images: ['https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?w=800&q=80'],
    rating: 4.5,
    orderedDishes: ['剁椒鱼头'],
    likes: 198,
    comments: [],
    createdAt: '2024-03-15'
  }
];

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: '学子居黄焖鸡',
    campus: '清华校区',
    category: '中式快餐',
    avgPrice: 25,
    rating: 4.5,
    distance: 0.3,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 156,
    tags: ['一人食', '宿舍外卖', '平价'],
    image: 'https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?w=600&q=80', // Braised chicken
    description: '经典的黄焖鸡米饭，浓郁的汤汁拌饭简直一绝，是学生党的外卖首选。',
    businessHours: '10:00 - 22:00',
    location: { lat: 39.99, lng: 116.32, address: '清华大学西门外100米' },
    savingTip: '美团外卖领券后仅需19.9元，到店出示学生证可免费加饭。',
    recommendedDishes: [
      { name: '招牌黄焖鸡', calories: 650, protein: 35, carbs: 45, fat: 28, price: 22, healthTags: ['高蛋白'] },
      { name: '香辣排骨饭', calories: 720, protein: 30, carbs: 50, fat: 32, price: 28, healthTags: [] }
    ],
    menu: [
      { name: '招牌黄焖鸡', calories: 650, protein: 35, carbs: 45, fat: 28, price: 22, healthTags: ['高蛋白'] },
      { name: '香辣排骨饭', calories: 720, protein: 30, carbs: 50, fat: 32, price: 28, healthTags: [] },
      { name: '土豆炖牛肉', calories: 580, protein: 28, carbs: 40, fat: 22, price: 26, healthTags: [] },
      { name: '酸辣土豆丝', calories: 220, protein: 4, carbs: 35, fat: 8, price: 12, healthTags: ['低脂'] },
      { name: '西红柿炒鸡蛋', calories: 310, protein: 12, carbs: 15, fat: 22, price: 15, healthTags: [] },
      { name: '青椒肉丝', calories: 420, protein: 22, carbs: 12, fat: 30, price: 20, healthTags: [] },
      { name: '麻婆豆腐', calories: 350, protein: 15, carbs: 10, fat: 25, price: 15, healthTags: [] },
      { name: '地三鲜', calories: 480, protein: 6, carbs: 45, fat: 32, price: 18, healthTags: [] },
      { name: '鱼香肉丝', calories: 450, protein: 20, carbs: 25, fat: 28, price: 22, healthTags: [] },
      { name: '紫菜蛋花汤', calories: 80, protein: 4, carbs: 5, fat: 4, price: 5, healthTags: ['低卡'] }
    ],
    taste: ['咸鲜', '微辣'],
    cuisineType: ['饭']
  },
  {
    id: '2',
    name: '绿野轻食社',
    campus: '北大校区',
    category: '健康轻食',
    avgPrice: 45,
    rating: 4.8,
    distance: 0.5,
    isNew: true,
    isHealthyFriendly: true,
    hasStudentDeal: false,
    yesterdayOrders: 89,
    tags: ['健身轻食', '减脂', '低卡'],
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80', // Salad
    description: '专注于低卡、高蛋白的健康饮食，所有食材均经过严格热量计算。',
    businessHours: '09:00 - 21:00',
    location: { lat: 39.98, lng: 116.31, address: '北京大学东门商业街2层' },
    savingTip: '办理周卡可享受8.5折优惠，适合长期健身的同学。',
    recommendedDishes: [
      { name: '香煎鸡胸肉沙拉', calories: 380, protein: 42, carbs: 15, fat: 12, price: 38, healthTags: ['低脂', '高蛋白', '低卡'] },
      { name: '牛油果大虾波奇饭', calories: 450, protein: 28, carbs: 40, fat: 18, price: 48, healthTags: ['优质脂肪', '轻食'] }
    ],
    menu: [
      { name: '香煎鸡胸肉沙拉', calories: 380, protein: 42, carbs: 15, fat: 12, price: 38, healthTags: ['低脂', '高蛋白', '低卡'] },
      { name: '牛油果大虾波奇饭', calories: 450, protein: 28, carbs: 40, fat: 18, price: 48, healthTags: ['优质脂肪', '轻食'] },
      { name: '烟熏三文鱼全麦卷', calories: 320, protein: 22, carbs: 30, fat: 14, price: 42, healthTags: ['低卡', '高蛋白'] },
      { name: '藜麦时蔬能量碗', calories: 280, protein: 12, carbs: 45, fat: 8, price: 35, healthTags: ['素食', '低卡'] },
      { name: '慢炖牛肉谷物碗', calories: 520, protein: 35, carbs: 55, fat: 16, price: 52, healthTags: ['高蛋白'] },
      { name: '泰式酸辣无骨鸡爪', calories: 210, protein: 18, carbs: 10, fat: 12, price: 28, healthTags: ['低脂'] },
      { name: '羽衣甘蓝青苹果汁', calories: 120, protein: 2, carbs: 25, fat: 1, price: 22, healthTags: ['维C爆棚'] },
      { name: '烤南瓜坚果沙拉', calories: 260, protein: 6, carbs: 35, fat: 12, price: 32, healthTags: ['素食'] },
      { name: '希腊酸奶杯', calories: 180, protein: 15, carbs: 12, fat: 6, price: 25, healthTags: ['高蛋白'] },
      { name: '全麦坚果贝果', calories: 240, protein: 8, carbs: 42, fat: 4, price: 18, healthTags: ['低脂'] }
    ],
    taste: ['清淡'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '3',
    name: '深夜食堂拉面',
    campus: '人大校区',
    category: '日式料理',
    avgPrice: 35,
    rating: 4.6,
    distance: 0.8,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 210,
    tags: ['夜宵续命', '一人食', '暖胃'],
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80', // Ramen
    description: '浓郁的猪骨汤底，深夜里的一碗热拉面是赶论文时的最佳慰藉。',
    businessHours: '18:00 - 02:00',
    location: { lat: 39.97, lng: 116.33, address: '人民大学南路美食街' },
    savingTip: '晚上10点后第二碗半价，适合和室友一起拼单。',
    recommendedDishes: [
      { name: '博多豚骨拉面', calories: 850, protein: 25, carbs: 80, fat: 35, price: 32, healthTags: [] },
      { name: '地狱辣味拉面', calories: 820, protein: 24, carbs: 78, fat: 34, price: 35, healthTags: [] }
    ],
    menu: [
      { name: '博多豚骨拉面', calories: 850, protein: 25, carbs: 80, fat: 35, price: 32, healthTags: [] },
      { name: '地狱辣味拉面', calories: 820, protein: 24, carbs: 78, fat: 34, price: 35, healthTags: [] },
      { name: '日式煎饺', calories: 280, protein: 10, carbs: 30, fat: 12, price: 18, healthTags: [] },
      { name: '章鱼小丸子', calories: 320, protein: 8, carbs: 40, fat: 15, price: 22, healthTags: [] },
      { name: '黑蒜油拉面', calories: 880, protein: 26, carbs: 82, fat: 38, price: 38, healthTags: [] },
      { name: '叉烧拼盘', calories: 450, protein: 35, carbs: 5, fat: 32, price: 45, healthTags: ['高蛋白'] },
      { name: '溏心蛋', calories: 80, protein: 7, carbs: 1, fat: 6, price: 5, healthTags: [] },
      { name: '中华海草', calories: 60, protein: 2, carbs: 10, fat: 2, price: 12, healthTags: ['低脂'] },
      { name: '可尔必思', calories: 120, protein: 1, carbs: 28, fat: 0, price: 12, healthTags: [] },
      { name: '朝日啤酒', calories: 150, protein: 1, carbs: 12, fat: 0, price: 18, healthTags: [] }
    ],
    taste: ['咸鲜', '辛辣'],
    cuisineType: ['面']
  },
  {
    id: '4',
    name: '图书馆咖啡吧',
    campus: '清华校区',
    category: '简餐咖啡',
    avgPrice: 30,
    rating: 4.3,
    distance: 0.1,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: true,
    yesterdayOrders: 124,
    tags: ['图书馆速食', '学习氛围', '提神'],
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&q=80', // Coffee
    description: '位于图书馆一楼，提供快速便捷的简餐和高品质咖啡。',
    businessHours: '08:00 - 22:30',
    location: { lat: 39.991, lng: 116.321, address: '清华大学图书馆北馆1层' },
    savingTip: '自带杯购买咖啡立减5元，三明治+美式套餐仅需28元。',
    recommendedDishes: [
      { name: '全麦鸡肉三明治', calories: 320, protein: 18, carbs: 35, fat: 10, price: 22, healthTags: ['低卡', '轻食'] },
      { name: '燕麦拿铁', calories: 150, protein: 5, carbs: 20, fat: 6, price: 28, healthTags: ['低脂'] }
    ],
    menu: [
      { name: '全麦鸡肉三明治', calories: 320, protein: 18, carbs: 35, fat: 10, price: 22, healthTags: ['低卡', '轻食'] },
      { name: '燕麦拿铁', calories: 150, protein: 5, carbs: 20, fat: 6, price: 28, healthTags: ['低脂'] },
      { name: '美式咖啡', calories: 5, protein: 0, carbs: 1, fat: 0, price: 18, healthTags: ['零卡'] },
      { name: '蓝莓马芬', calories: 350, protein: 4, carbs: 45, fat: 18, price: 15, healthTags: [] },
      { name: '金枪鱼沙拉卷', calories: 290, protein: 20, carbs: 32, fat: 12, price: 25, healthTags: ['高蛋白'] },
      { name: '抹茶拿铁', calories: 180, protein: 6, carbs: 25, fat: 8, price: 32, healthTags: [] },
      { name: '提拉米苏', calories: 420, protein: 6, carbs: 48, fat: 22, price: 35, healthTags: [] },
      { name: '焦糖玛奇朵', calories: 250, protein: 8, carbs: 35, fat: 10, price: 35, healthTags: [] },
      { name: '火腿芝士牛角包', calories: 380, protein: 12, carbs: 30, fat: 24, price: 20, healthTags: [] },
      { name: '伯爵红茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 15, healthTags: ['零卡'] }
    ],
    taste: ['清淡'],
    cuisineType: ['饮品']
  },
  {
    id: '5',
    name: '聚义厅火锅',
    campus: '北航校区',
    category: '四川火锅',
    avgPrice: 85,
    rating: 4.7,
    distance: 1.2,
    isNew: true,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 342,
    tags: ['朋友聚餐', '约会氛围', '热闹'],
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=80', // Hotpot
    description: '正宗川味火锅，装修极具武侠风格，是社团聚餐的不二之选。',
    businessHours: '11:00 - 23:00',
    location: { lat: 39.985, lng: 116.34, address: '北航南门外商业广场3层' },
    savingTip: '凭学生证可享受菜品6.9折，生日当天赠送长寿面。',
    recommendedDishes: [
      { name: '麻辣锅底', calories: 1200, protein: 10, carbs: 20, fat: 110, price: 58, healthTags: [] },
      { name: '手切鲜羊肉', calories: 250, protein: 20, carbs: 0, fat: 18, price: 48, healthTags: ['高蛋白'] }
    ],
    menu: [
      { name: '麻辣锅底', calories: 1200, protein: 10, carbs: 20, fat: 110, price: 58, healthTags: [] },
      { name: '手切鲜羊肉', calories: 250, protein: 20, carbs: 0, fat: 18, price: 48, healthTags: ['高蛋白'] },
      { name: '极品肥牛', calories: 280, protein: 18, carbs: 0, fat: 22, price: 52, healthTags: ['高蛋白'] },
      { name: '功夫土豆片', calories: 120, protein: 2, carbs: 25, fat: 1, price: 12, healthTags: ['低脂'] },
      { name: '毛肚', calories: 80, protein: 12, carbs: 2, fat: 3, price: 38, healthTags: ['低卡'] },
      { name: '黄喉', calories: 90, protein: 14, carbs: 1, fat: 4, price: 35, healthTags: ['低卡'] },
      { name: '鸭血', calories: 60, protein: 10, carbs: 1, fat: 1, price: 15, healthTags: ['低脂'] },
      { name: '大白菜', calories: 20, protein: 1, carbs: 4, fat: 0, price: 8, healthTags: ['低卡', '素食'] },
      { name: '红糖糍粑', calories: 350, protein: 4, carbs: 65, fat: 10, price: 22, healthTags: [] },
      { name: '酸梅汤', calories: 120, protein: 0, carbs: 30, fat: 0, price: 10, healthTags: [] }
    ],
    taste: ['辛辣', '麻辣'],
    cuisineType: ['火锅']
  },
  {
    id: '6',
    name: '雨后森林西餐',
    campus: '北大校区',
    category: '西式料理',
    avgPrice: 120,
    rating: 4.9,
    distance: 0.6,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: false,
    yesterdayOrders: 67,
    tags: ['约会氛围', '下雨天最近', '精致'],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&q=80', // Western food
    description: '环境优雅，充满森林气息，非常适合情侣约会或纪念日庆祝。',
    businessHours: '11:30 - 21:30',
    location: { lat: 39.982, lng: 116.315, address: '北大西门林荫道旁' },
    savingTip: '双人浪漫套餐比单点优惠50元，需提前预约。',
    recommendedDishes: [
      { name: '澳洲M5和牛牛排', calories: 550, protein: 45, carbs: 5, fat: 38, price: 188, healthTags: ['高蛋白', '增肌友好'] },
      { name: '黑松露野菇意面', calories: 480, protein: 12, carbs: 65, fat: 20, price: 68, healthTags: [] }
    ],
    menu: [
      { name: '澳洲M5和牛牛排', calories: 550, protein: 45, carbs: 5, fat: 38, price: 188, healthTags: ['高蛋白', '增肌友好'] },
      { name: '黑松露野菇意面', calories: 480, protein: 12, carbs: 65, fat: 20, price: 68, healthTags: [] },
      { name: '凯撒沙拉', calories: 220, protein: 8, carbs: 12, fat: 15, price: 45, healthTags: ['低卡'] },
      { name: '法式洋葱汤', calories: 180, protein: 6, carbs: 15, fat: 10, price: 32, healthTags: [] },
      { name: '香煎三文鱼', calories: 320, protein: 28, carbs: 2, fat: 22, price: 128, healthTags: ['优质脂肪', '高蛋白'] },
      { name: '波士顿龙虾卷', calories: 420, protein: 25, carbs: 35, fat: 20, price: 158, healthTags: [] },
      { name: '奶油蘑菇汤', calories: 280, protein: 4, carbs: 18, fat: 22, price: 38, healthTags: [] },
      { name: '经典提拉米苏', calories: 450, protein: 7, carbs: 42, fat: 28, price: 48, healthTags: [] },
      { name: '红酒烩牛肉', calories: 520, protein: 38, carbs: 15, fat: 32, price: 98, healthTags: ['高蛋白'] },
      { name: '气泡矿泉水', calories: 0, protein: 0, carbs: 0, fat: 0, price: 25, healthTags: ['零卡'] }
    ],
    taste: ['咸鲜', '清淡'],
    cuisineType: ['饭', '面', '饮品']
  },
  {
    id: '7',
    name: '川香阁',
    campus: '人大校区',
    category: '川菜',
    avgPrice: 40,
    rating: 4.4,
    distance: 0.4,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 198,
    tags: ['朋友聚餐', '宿舍外卖', '重口味'],
    image: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?w=600&q=80', // Sichuan food
    description: '地道川菜，麻辣鲜香，分量十足。',
    businessHours: '10:30 - 22:00',
    location: { lat: 39.975, lng: 116.325, address: '人大东门美食街' },
    savingTip: '满50减10元，学生证9折。',
    recommendedDishes: [
      { name: '麻婆豆腐', calories: 350, protein: 15, carbs: 10, fat: 25, price: 18, healthTags: [] },
      { name: '回锅肉', calories: 580, protein: 22, carbs: 5, fat: 50, price: 38, healthTags: [] }
    ],
    menu: [
      { name: '麻婆豆腐', calories: 350, protein: 15, carbs: 10, fat: 25, price: 18, healthTags: [] },
      { name: '回锅肉', calories: 580, protein: 22, carbs: 5, fat: 50, price: 38, healthTags: [] },
      { name: '宫保鸡丁', calories: 450, protein: 25, carbs: 15, fat: 30, price: 32, healthTags: ['高蛋白'] },
      { name: '鱼香肉丝', calories: 420, protein: 20, carbs: 25, fat: 28, price: 28, healthTags: [] },
      { name: '水煮鱼', calories: 950, protein: 45, carbs: 10, fat: 80, price: 68, healthTags: ['高蛋白'] },
      { name: '辣子鸡', calories: 620, protein: 35, carbs: 12, fat: 48, price: 45, healthTags: ['高蛋白'] },
      { name: '干煸豆角', calories: 280, protein: 6, carbs: 15, fat: 22, price: 22, healthTags: [] },
      { name: '蒜泥白肉', calories: 480, protein: 18, carbs: 5, fat: 42, price: 32, healthTags: [] },
      { name: '酸辣粉', calories: 380, protein: 4, carbs: 65, fat: 12, price: 15, healthTags: [] },
      { name: '冰粉', calories: 120, protein: 1, carbs: 28, fat: 0, price: 8, healthTags: ['低脂'] }
    ],
    taste: ['麻辣', '辛辣'],
    cuisineType: ['饭', '面']
  },
  {
    id: '8',
    name: '老北京炸酱面',
    campus: '清华校区',
    category: '面食',
    avgPrice: 20,
    rating: 4.2,
    distance: 0.2,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 245,
    tags: ['一人食', '图书馆速食', '平价'],
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&q=80', // Noodles
    description: '传统手擀面，酱香浓郁，配菜丰富。',
    businessHours: '09:00 - 21:00',
    location: { lat: 39.992, lng: 116.322, address: '清华大学北门外' },
    savingTip: '加面免费，学生套餐仅需18元。',
    recommendedDishes: [
      { name: '招牌炸酱面', calories: 550, protein: 18, carbs: 85, fat: 15, price: 20, healthTags: [] }
    ],
    menu: [
      { name: '招牌炸酱面', calories: 550, protein: 18, carbs: 85, fat: 15, price: 20, healthTags: [] },
      { name: '打卤面', calories: 520, protein: 15, carbs: 80, fat: 12, price: 18, healthTags: [] },
      { name: '凉拌黄瓜', calories: 80, protein: 2, carbs: 5, fat: 6, price: 8, healthTags: ['低脂', '低卡'] },
      { name: '西红柿鸡蛋面', calories: 480, protein: 14, carbs: 75, fat: 15, price: 16, healthTags: [] },
      { name: '老北京豆汁', calories: 40, protein: 3, carbs: 6, fat: 1, price: 5, healthTags: ['特色'] },
      { name: '焦圈', calories: 180, protein: 2, carbs: 20, fat: 12, price: 3, healthTags: [] },
      { name: '芥末墩', calories: 60, protein: 2, carbs: 8, fat: 2, price: 12, healthTags: ['低脂'] },
      { name: '爆肚', calories: 220, protein: 28, carbs: 4, fat: 10, price: 35, healthTags: ['高蛋白'] },
      { name: '驴打滚', calories: 280, protein: 4, carbs: 55, fat: 6, price: 15, healthTags: [] },
      { name: '酸梅汤', calories: 100, protein: 0, carbs: 25, fat: 0, price: 6, healthTags: [] }
    ],
    taste: ['咸鲜'],
    cuisineType: ['面']
  },
  {
    id: '9',
    name: '汉堡王',
    campus: '北航校区',
    category: '西式快餐',
    avgPrice: 35,
    rating: 4.1,
    distance: 0.5,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 312,
    tags: ['宿舍外卖', '图书馆速食', '快捷'],
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80', // Burger
    description: '火烤牛肉，多汁美味。',
    businessHours: '08:00 - 23:00',
    location: { lat: 39.986, lng: 116.341, address: '北航南门商业街' },
    savingTip: '周三会员日买一送一。',
    recommendedDishes: [
      { name: '皇堡', calories: 670, protein: 28, carbs: 49, fat: 38, price: 32, healthTags: [] }
    ],
    menu: [
      { name: '皇堡', calories: 670, protein: 28, carbs: 49, fat: 38, price: 32, healthTags: [] },
      { name: '薯条', calories: 320, protein: 3, carbs: 40, fat: 17, price: 12, healthTags: [] },
      { name: '可乐', calories: 150, protein: 0, carbs: 38, fat: 0, price: 10, healthTags: [] },
      { name: '天椒皇堡', calories: 690, protein: 29, carbs: 50, fat: 40, price: 35, healthTags: [] },
      { name: '狠牛牛堡', calories: 580, protein: 25, carbs: 45, fat: 32, price: 28, healthTags: [] },
      { name: '鸡米花', calories: 350, protein: 18, carbs: 25, fat: 22, price: 15, healthTags: [] },
      { name: '洋葱圈', calories: 280, protein: 4, carbs: 32, fat: 16, price: 12, healthTags: [] },
      { name: '嫩烤鸡腿堡', calories: 450, protein: 22, carbs: 42, fat: 22, price: 25, healthTags: [] },
      { name: '新地', calories: 220, protein: 4, carbs: 35, fat: 8, price: 10, healthTags: [] },
      { name: '热巧克力', calories: 180, protein: 5, carbs: 28, fat: 6, price: 12, healthTags: [] }
    ],
    taste: ['咸鲜'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '10',
    name: '泰好味',
    campus: '北大校区',
    category: '东南亚菜',
    avgPrice: 65,
    rating: 4.6,
    distance: 0.9,
    isNew: true,
    isHealthyFriendly: true,
    hasStudentDeal: false,
    yesterdayOrders: 145,
    tags: ['约会氛围', '朋友聚餐', '异域风情'],
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80', // Thai food
    description: '正宗泰式料理，冬阴功汤酸辣开胃。',
    businessHours: '11:00 - 22:00',
    location: { lat: 39.981, lng: 116.312, address: '北大西门商业区' },
    savingTip: '新店开业8折优惠。',
    recommendedDishes: [
      { name: '冬阴功汤', calories: 280, protein: 12, carbs: 15, fat: 18, price: 48, healthTags: ['低卡'] },
      { name: '菠萝炒饭', calories: 520, protein: 15, carbs: 85, fat: 12, price: 42, healthTags: [] }
    ],
    menu: [
      { name: '冬阴功汤', calories: 280, protein: 12, carbs: 15, fat: 18, price: 48, healthTags: ['低卡'] },
      { name: '菠萝炒饭', calories: 520, protein: 15, carbs: 85, fat: 12, price: 42, healthTags: [] },
      { name: '泰式青木瓜沙拉', calories: 150, protein: 4, carbs: 20, fat: 6, price: 28, healthTags: ['低脂', '低卡'] },
      { name: '黄咖喱鸡', calories: 480, protein: 25, carbs: 20, fat: 35, price: 52, healthTags: ['高蛋白'] },
      { name: '泰式明炉鱼', calories: 350, protein: 38, carbs: 5, fat: 18, price: 88, healthTags: ['高蛋白', '低脂'] },
      { name: '芒果糯米饭', calories: 420, protein: 5, carbs: 80, fat: 10, price: 32, healthTags: [] },
      { name: '泰式手打虾饼', calories: 320, protein: 22, carbs: 15, fat: 18, price: 45, healthTags: ['高蛋白'] },
      { name: '沙爹鸡肉串', calories: 280, protein: 24, carbs: 8, fat: 16, price: 35, healthTags: ['高蛋白'] },
      { name: '泰式奶茶', calories: 220, protein: 3, carbs: 35, fat: 8, price: 18, healthTags: [] },
      { name: '椰子冻', calories: 180, protein: 2, carbs: 25, fat: 10, price: 25, healthTags: [] }
    ],
    taste: ['酸辣', '辛辣'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '11',
    name: '麻辣烫小站',
    campus: '人大校区',
    category: '小吃',
    avgPrice: 22,
    rating: 4.3,
    distance: 0.3,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: true,
    yesterdayOrders: 278,
    tags: ['一人食', '夜宵续命', '平价'],
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80', // Malatang
    description: '自选食材，多种汤底可选。',
    businessHours: '10:00 - 00:00',
    location: { lat: 39.976, lng: 116.326, address: '人大西门美食街' },
    savingTip: '称重计费，满20元送饮料。',
    recommendedDishes: [
      { name: '自选麻辣烫', calories: 450, protein: 25, carbs: 30, fat: 20, price: 25, healthTags: ['高蛋白', '多蔬菜'] }
    ],
    menu: [
      { name: '自选麻辣烫', calories: 450, protein: 25, carbs: 30, fat: 20, price: 25, healthTags: ['高蛋白', '多蔬菜'] },
      { name: '酸辣粉', calories: 380, protein: 4, carbs: 65, fat: 12, price: 15, healthTags: [] },
      { name: '红薯粉', calories: 320, protein: 2, carbs: 75, fat: 1, price: 12, healthTags: ['低脂'] },
      { name: '鱼豆腐', calories: 120, protein: 8, carbs: 10, fat: 6, price: 3, healthTags: [] },
      { name: '蟹柳', calories: 90, protein: 6, carbs: 12, fat: 2, price: 3, healthTags: [] },
      { name: '午餐肉', calories: 250, protein: 12, carbs: 5, fat: 22, price: 5, healthTags: [] },
      { name: '金针菇', calories: 30, protein: 2, carbs: 6, fat: 0, price: 2, healthTags: ['低卡', '素食'] },
      { name: '娃娃菜', calories: 20, protein: 1, carbs: 4, fat: 0, price: 2, healthTags: ['低卡', '素食'] },
      { name: '宽粉', calories: 280, protein: 1, carbs: 68, fat: 0, price: 3, healthTags: [] },
      { name: '冰镇豆奶', calories: 150, protein: 6, carbs: 20, fat: 5, price: 5, healthTags: [] }
    ],
    taste: ['麻辣', '辛辣'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '12',
    name: '韩式炸鸡屋',
    campus: '清华校区',
    category: '韩式料理',
    avgPrice: 50,
    rating: 4.5,
    distance: 0.7,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: false,
    yesterdayOrders: 167,
    tags: ['宿舍外卖', '朋友聚餐', '解馋'],
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&q=80', // Fried chicken
    description: '外酥里嫩，多种酱料可选。',
    businessHours: '11:00 - 23:00',
    location: { lat: 39.993, lng: 116.323, address: '清华东门外' },
    savingTip: '双人套餐更划算。',
    recommendedDishes: [
      { name: '蜂蜜芥末炸鸡', calories: 880, protein: 35, carbs: 45, fat: 60, price: 58, healthTags: [] }
    ],
    menu: [
      { name: '蜂蜜芥末炸鸡', calories: 880, protein: 35, carbs: 45, fat: 60, price: 58, healthTags: [] },
      { name: '甜辣炸鸡', calories: 850, protein: 34, carbs: 48, fat: 58, price: 58, healthTags: [] },
      { name: '原味脆皮炸鸡', calories: 820, protein: 36, carbs: 40, fat: 55, price: 52, healthTags: [] },
      { name: '芝士炸鸡', calories: 920, protein: 38, carbs: 42, fat: 65, price: 62, healthTags: [] },
      { name: '韩式石锅拌饭', calories: 550, protein: 18, carbs: 85, fat: 15, price: 35, healthTags: [] },
      { name: '辛拉面', calories: 480, protein: 10, carbs: 75, fat: 15, price: 25, healthTags: [] },
      { name: '炒年糕', calories: 420, protein: 6, carbs: 88, fat: 5, price: 28, healthTags: [] },
      { name: '海鲜葱饼', calories: 350, protein: 15, carbs: 45, fat: 12, price: 32, healthTags: [] },
      { name: '大酱汤', calories: 220, protein: 12, carbs: 15, fat: 12, price: 28, healthTags: [] },
      { name: '烧酒', calories: 240, protein: 0, carbs: 10, fat: 0, price: 25, healthTags: [] }
    ],
    taste: ['甜辣', '辛辣'],
    cuisineType: ['饭', '面', '饮品']
  },
  {
    id: '13',
    name: '素食坊',
    campus: '北大校区',
    category: '素食',
    avgPrice: 35,
    rating: 4.7,
    distance: 0.4,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: true,
    yesterdayOrders: 92,
    tags: ['健康轻食', '减脂', '清淡'],
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80', // Veggie
    description: '纯天然食材，健康美味。',
    businessHours: '10:00 - 21:00',
    location: { lat: 39.983, lng: 116.313, address: '北大校内餐饮中心' },
    savingTip: '学生证8.5折。',
    recommendedDishes: [
      { name: '五彩拌饭', calories: 320, protein: 10, carbs: 60, fat: 5, price: 28, healthTags: ['低脂', '低卡'] }
    ],
    menu: [
      { name: '五彩拌饭', calories: 320, protein: 10, carbs: 60, fat: 5, price: 28, healthTags: ['低脂', '低卡'] },
      { name: '素三鲜饺子', calories: 350, protein: 12, carbs: 55, fat: 10, price: 22, healthTags: ['素食'] },
      { name: '荷塘月色', calories: 180, protein: 4, carbs: 25, fat: 8, price: 32, healthTags: ['低脂', '清淡'] },
      { name: '罗汉斋', calories: 220, protein: 8, carbs: 30, fat: 10, price: 35, healthTags: ['素食'] },
      { name: '手撕包菜', calories: 150, protein: 3, carbs: 12, fat: 12, price: 18, healthTags: [] },
      { name: '清炒时蔬', calories: 120, protein: 2, carbs: 8, fat: 10, price: 15, healthTags: ['低脂'] },
      { name: '南瓜粥', calories: 120, protein: 2, carbs: 28, fat: 1, price: 8, healthTags: ['低卡'] },
      { name: '素春卷', calories: 240, protein: 4, carbs: 35, fat: 12, price: 12, healthTags: [] },
      { name: '凉拌木耳', calories: 90, protein: 3, carbs: 10, fat: 6, price: 15, healthTags: ['低脂'] },
      { name: '鲜榨玉米汁', calories: 160, protein: 4, carbs: 32, fat: 2, price: 15, healthTags: [] }
    ],
    taste: ['清淡'],
    cuisineType: ['饭']
  },
  {
    id: '14',
    name: '新疆大串',
    campus: '北航校区',
    category: '烧烤',
    avgPrice: 55,
    rating: 4.4,
    distance: 0.8,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: false,
    yesterdayOrders: 423,
    tags: ['夜宵续命', '朋友聚餐', '肉食动物'],
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80', // BBQ
    description: '正宗红柳大串，肉质鲜嫩。',
    businessHours: '17:00 - 02:00',
    location: { lat: 39.987, lng: 116.342, address: '北航东门外' },
    savingTip: '买10串送1串。',
    recommendedDishes: [
      { name: '红柳烤羊肉', calories: 150, protein: 15, carbs: 0, fat: 10, price: 12, healthTags: ['高蛋白'] }
    ],
    menu: [
      { name: '红柳烤羊肉', calories: 150, protein: 15, carbs: 0, fat: 10, price: 12, healthTags: ['高蛋白'] },
      { name: '烤牛肉串', calories: 130, protein: 14, carbs: 0, fat: 8, price: 10, healthTags: ['高蛋白'] },
      { name: '烤鸡翅', calories: 220, protein: 18, carbs: 2, fat: 16, price: 15, healthTags: [] },
      { name: '烤板筋', calories: 110, protein: 12, carbs: 1, fat: 6, price: 8, healthTags: [] },
      { name: '烤生蚝', calories: 80, protein: 8, carbs: 5, fat: 4, price: 12, healthTags: [] },
      { name: '烤茄子', calories: 180, protein: 2, carbs: 15, fat: 14, price: 15, healthTags: [] },
      { name: '烤玉米', calories: 150, protein: 4, carbs: 30, fat: 2, price: 8, healthTags: [] },
      { name: '新疆大馕', calories: 450, protein: 12, carbs: 90, fat: 5, price: 10, healthTags: [] },
      { name: '羊肉手抓饭', calories: 680, protein: 25, carbs: 85, fat: 28, price: 38, healthTags: [] },
      { name: '卡瓦斯', calories: 120, protein: 0, carbs: 30, fat: 0, price: 12, healthTags: [] }
    ],
    taste: ['咸鲜', '辛辣'],
    cuisineType: ['饭']
  },
  {
    id: '15',
    name: '港式茶餐厅',
    campus: '人大校区',
    category: '粤菜',
    avgPrice: 60,
    rating: 4.5,
    distance: 0.6,
    isNew: true,
    isHealthyFriendly: true,
    hasStudentDeal: false,
    yesterdayOrders: 134,
    tags: ['约会氛围', '朋友聚餐', '精致'],
    image: 'https://images.unsplash.com/photo-1583182332473-b31ba08929c8?w=600&q=80', // HK food
    description: '经典港式点心，丝滑奶茶。',
    businessHours: '08:00 - 22:00',
    location: { lat: 39.977, lng: 116.327, address: '人大北门外' },
    savingTip: '下午茶时段套餐6折。',
    recommendedDishes: [
      { name: '水晶虾饺', calories: 180, protein: 10, carbs: 25, fat: 5, price: 28, healthTags: ['低脂'] },
      { name: '冰镇奶茶', calories: 250, protein: 3, carbs: 40, fat: 8, price: 18, healthTags: [] }
    ],
    menu: [
      { name: '水晶虾饺', calories: 180, protein: 10, carbs: 25, fat: 5, price: 28, healthTags: ['低脂'] },
      { name: '冰镇奶茶', calories: 250, protein: 3, carbs: 40, fat: 8, price: 18, healthTags: [] },
      { name: '干炒牛河', calories: 650, protein: 22, carbs: 85, fat: 28, price: 35, healthTags: [] },
      { name: '蜜汁叉烧包', calories: 280, protein: 8, carbs: 45, fat: 10, price: 18, healthTags: [] },
      { name: '烧鹅拼盘', calories: 550, protein: 35, carbs: 5, fat: 45, price: 88, healthTags: ['高蛋白'] },
      { name: '豉汁蒸凤爪', calories: 220, protein: 12, carbs: 5, fat: 18, price: 22, healthTags: [] },
      { name: '腊味煲仔饭', calories: 720, protein: 20, carbs: 95, fat: 30, price: 38, healthTags: [] },
      { name: '云吞面', calories: 420, protein: 18, carbs: 65, fat: 12, price: 25, healthTags: [] },
      { name: '菠萝油', calories: 380, protein: 6, carbs: 50, fat: 18, price: 12, healthTags: [] },
      { name: '杨枝甘露', calories: 280, protein: 4, carbs: 55, fat: 6, price: 25, healthTags: [] }
    ],
    taste: ['清淡', '咸鲜'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '16',
    name: '老西安肉夹馍',
    campus: '清华校区',
    category: '小吃',
    avgPrice: 18,
    rating: 4.3,
    distance: 0.2,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 289,
    tags: ['一人食', '图书馆速食', '平价'],
    image: 'https://images.unsplash.com/photo-1623341214825-9f4f963727da?w=600&q=80', // Roujiamo
    description: '饼酥肉香，肥而不腻。',
    businessHours: '07:00 - 21:00',
    location: { lat: 39.994, lng: 116.324, address: '清华西门商业街' },
    savingTip: '肉夹馍+凉皮套餐仅需25元。',
    recommendedDishes: [
      { name: '腊汁肉夹馍', calories: 420, protein: 18, carbs: 45, fat: 20, price: 12, healthTags: [] }
    ],
    menu: [
      { name: '腊汁肉夹馍', calories: 420, protein: 18, carbs: 45, fat: 20, price: 12, healthTags: [] },
      { name: '陕西凉皮', calories: 350, protein: 6, carbs: 75, fat: 5, price: 12, healthTags: ['低脂'] },
      { name: '羊肉泡馍', calories: 780, protein: 35, carbs: 95, fat: 32, price: 38, healthTags: ['高蛋白'] },
      { name: '油泼面', calories: 620, protein: 15, carbs: 90, fat: 25, price: 18, healthTags: [] },
      { name: '岐山臊子面', calories: 580, protein: 18, carbs: 85, fat: 22, price: 20, healthTags: [] },
      { name: '冰峰汽水', calories: 150, protein: 0, carbs: 38, fat: 0, price: 5, healthTags: [] },
      { name: 'biangbiang面', calories: 650, protein: 16, carbs: 95, fat: 28, price: 22, healthTags: [] },
      { name: '酸汤水饺', calories: 450, protein: 18, carbs: 65, fat: 15, price: 22, healthTags: [] },
      { name: '凉拌面皮', calories: 320, protein: 5, carbs: 70, fat: 4, price: 10, healthTags: ['低脂'] },
      { name: '红枣甑糕', calories: 380, protein: 6, carbs: 85, fat: 2, price: 15, healthTags: [] }
    ],
    taste: ['咸鲜'],
    cuisineType: ['面']
  },
  {
    id: '17',
    name: '意式披萨屋',
    campus: '北大校区',
    category: '西式料理',
    avgPrice: 75,
    rating: 4.6,
    distance: 1.1,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 178,
    tags: ['朋友聚餐', '宿舍外卖', '聚会'],
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80', // Pizza
    description: '薄底披萨，芝士浓郁。',
    businessHours: '11:00 - 22:00',
    location: { lat: 39.984, lng: 116.314, address: '北大东门外' },
    savingTip: '凭学生证披萨买一送一。',
    recommendedDishes: [
      { name: '玛格丽特披萨', calories: 850, protein: 35, carbs: 110, fat: 30, price: 68, healthTags: [] }
    ],
    menu: [
      { name: '玛格丽特披萨', calories: 850, protein: 35, carbs: 110, fat: 30, price: 68, healthTags: [] },
      { name: '意式腊肠披萨', calories: 980, protein: 42, carbs: 115, fat: 42, price: 78, healthTags: [] },
      { name: '奶油培根面', calories: 620, protein: 22, carbs: 75, fat: 28, price: 45, healthTags: [] },
      { name: '番茄肉酱面', calories: 550, protein: 25, carbs: 80, fat: 18, price: 42, healthTags: [] },
      { name: '意式烤鸡翅', calories: 320, protein: 28, carbs: 5, fat: 22, price: 35, healthTags: ['高蛋白'] },
      { name: '提拉米苏', calories: 420, protein: 6, carbs: 48, fat: 22, price: 38, healthTags: [] },
      { name: '意式蔬菜汤', calories: 120, protein: 4, carbs: 15, fat: 5, price: 25, healthTags: ['低脂', '低卡'] },
      { name: '蒜香面包', calories: 250, protein: 5, carbs: 35, fat: 12, price: 15, healthTags: [] },
      { name: '芝士焗饭', calories: 680, protein: 28, carbs: 85, fat: 28, price: 52, healthTags: [] },
      { name: '意式特浓咖啡', calories: 5, protein: 0, carbs: 1, fat: 0, price: 18, healthTags: ['零卡'] }
    ],
    taste: ['咸鲜', '清淡'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '18',
    name: '潮汕牛肉火锅',
    campus: '北航校区',
    category: '火锅',
    avgPrice: 95,
    rating: 4.8,
    distance: 1.5,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: false,
    yesterdayOrders: 256,
    tags: ['朋友聚餐', '健身轻食', '高品质'],
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&q=80', // Beef hotpot
    description: '鲜切牛肉，清汤锅底，原汁原味。',
    businessHours: '11:00 - 22:00',
    location: { lat: 39.988, lng: 116.343, address: '北航北门外' },
    savingTip: '午市菜品8折。',
    recommendedDishes: [
      { name: '吊龙肉', calories: 180, protein: 25, carbs: 0, fat: 8, price: 42, healthTags: ['高蛋白', '低脂'] }
    ],
    menu: [
      { name: '吊龙肉', calories: 180, protein: 25, carbs: 0, fat: 8, price: 42, healthTags: ['高蛋白', '低脂'] },
      { name: '五花趾', calories: 220, protein: 22, carbs: 0, fat: 14, price: 48, healthTags: ['高蛋白'] },
      { name: '匙仁', calories: 190, protein: 24, carbs: 0, fat: 10, price: 45, healthTags: ['高蛋白'] },
      { name: '手打牛肉丸', calories: 250, protein: 20, carbs: 5, fat: 18, price: 38, healthTags: ['高蛋白'] },
      { name: '牛骨清汤锅', calories: 150, protein: 10, carbs: 2, fat: 12, price: 38, healthTags: ['低卡'] },
      { name: '炸腐竹', calories: 320, protein: 15, carbs: 10, fat: 25, price: 15, healthTags: [] },
      { name: '潮汕粿条', calories: 280, protein: 4, carbs: 65, fat: 1, price: 12, healthTags: ['低脂'] },
      { name: '生菜', calories: 20, protein: 1, carbs: 4, fat: 0, price: 8, healthTags: ['低卡', '素食'] },
      { name: '沙茶酱', calories: 150, protein: 2, carbs: 8, fat: 12, price: 5, healthTags: [] },
      { name: '单丛茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 10, healthTags: ['零卡'] }
    ],
    taste: ['清淡', '咸鲜'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '19',
    name: '兰州拉面',
    campus: '人大校区',
    category: '面食',
    avgPrice: 15,
    rating: 4.1,
    distance: 0.1,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 512,
    tags: ['一人食', '平价', '快捷'],
    image: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=600&q=80', // Lanzhou noodles
    description: '一清二白三红四绿五黄。',
    businessHours: '06:00 - 23:00',
    location: { lat: 39.978, lng: 116.328, address: '人大南门外' },
    savingTip: '加面免费。',
    recommendedDishes: [
      { name: '牛肉拉面', calories: 520, protein: 20, carbs: 80, fat: 12, price: 15, healthTags: [] }
    ],
    menu: [
      { name: '牛肉拉面', calories: 520, protein: 20, carbs: 80, fat: 12, price: 15, healthTags: [] },
      { name: '牛肉炒面', calories: 650, protein: 22, carbs: 85, fat: 25, price: 18, healthTags: [] },
      { name: '大盘鸡', calories: 1200, protein: 85, carbs: 95, fat: 65, price: 68, healthTags: ['高蛋白'] },
      { name: '羊肉串', calories: 120, protein: 12, carbs: 0, fat: 8, price: 5, healthTags: ['高蛋白'] },
      { name: '葱油饼', calories: 280, protein: 5, carbs: 45, fat: 10, price: 8, healthTags: [] },
      { name: '凉拌三丝', calories: 120, protein: 3, carbs: 15, fat: 6, price: 10, healthTags: ['低脂'] },
      { name: '鸡蛋炒面', calories: 580, protein: 15, carbs: 82, fat: 22, price: 15, healthTags: [] },
      { name: '牛肉泡馍', calories: 750, protein: 32, carbs: 90, fat: 28, price: 35, healthTags: ['高蛋白'] },
      { name: '酸奶', calories: 150, protein: 6, carbs: 18, fat: 6, price: 8, healthTags: [] },
      { name: '红茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 2, healthTags: ['零卡'] }
    ],
    taste: ['咸鲜', '辛辣'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '20',
    name: '粥店',
    campus: '清华校区',
    category: '中式快餐',
    avgPrice: 28,
    rating: 4.4,
    distance: 0.4,
    isNew: false,
    isHealthyFriendly: true,
    hasStudentDeal: true,
    yesterdayOrders: 143,
    tags: ['一人食', '暖胃', '健康轻食'],
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80', // Porridge
    description: '各种养生粥品，清淡适口。',
    businessHours: '07:00 - 22:00',
    location: { lat: 39.995, lng: 116.325, address: '清华校内食堂' },
    savingTip: '学生卡消费9折。',
    recommendedDishes: [
      { name: '皮蛋瘦肉粥', calories: 250, protein: 12, carbs: 40, fat: 5, price: 12, healthTags: ['低脂'] }
    ],
    menu: [
      { name: '皮蛋瘦肉粥', calories: 250, protein: 12, carbs: 40, fat: 5, price: 12, healthTags: ['低脂'] },
      { name: '南瓜小米粥', calories: 180, protein: 4, carbs: 38, fat: 1, price: 10, healthTags: ['低脂', '低卡'] },
      { name: '香菇鸡肉粥', calories: 220, protein: 15, carbs: 35, fat: 4, price: 15, healthTags: ['低脂', '高蛋白'] },
      { name: '海鲜粥', calories: 280, protein: 18, carbs: 42, fat: 6, price: 25, healthTags: ['优质蛋白'] },
      { name: '蒸饺', calories: 320, protein: 12, carbs: 45, fat: 12, price: 15, healthTags: [] },
      { name: '小笼包', calories: 350, protein: 15, carbs: 40, fat: 18, price: 18, healthTags: [] },
      { name: '茶叶蛋', calories: 80, protein: 7, carbs: 1, fat: 6, price: 2, healthTags: ['高蛋白'] },
      { name: '凉拌海带丝', calories: 60, protein: 2, carbs: 8, fat: 3, price: 8, healthTags: ['低脂', '低卡'] },
      { name: '油条', calories: 280, protein: 4, carbs: 30, fat: 18, price: 3, healthTags: [] },
      { name: '豆浆', calories: 120, protein: 8, carbs: 12, fat: 5, price: 4, healthTags: ['高蛋白'] }
    ],
    taste: ['清淡'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '21',
    name: '云南过桥米线',
    campus: '北大校区',
    category: '面食',
    avgPrice: 32,
    rating: 4.5,
    distance: 0.5,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 187,
    tags: ['一人食', '暖胃', '宿舍外卖'],
    image: 'https://images.unsplash.com/photo-1512058560366-cd242959b4fe?w=600&q=80', // Rice noodles
    description: '汤鲜味美，配料丰富。',
    businessHours: '10:00 - 22:00',
    location: { lat: 39.985, lng: 116.315, address: '北大西门外' },
    savingTip: '满30减5元。',
    recommendedDishes: [
      { name: '招牌过桥米线', calories: 620, protein: 22, carbs: 85, fat: 18, price: 32, healthTags: [] }
    ],
    menu: [
      { name: '招牌过桥米线', calories: 620, protein: 22, carbs: 85, fat: 18, price: 32, healthTags: [] },
      { name: '酸汤肥牛米线', calories: 580, protein: 25, carbs: 80, fat: 22, price: 35, healthTags: [] },
      { name: '番茄丸子米线', calories: 480, protein: 18, carbs: 75, fat: 12, price: 28, healthTags: [] },
      { name: '麻辣排骨米线', calories: 650, protein: 20, carbs: 82, fat: 28, price: 32, healthTags: [] },
      { name: '汽锅鸡', calories: 350, protein: 42, carbs: 5, fat: 18, price: 58, healthTags: ['高蛋白'] },
      { name: '大理乳扇', calories: 220, protein: 12, carbs: 15, fat: 14, price: 22, healthTags: [] },
      { name: '鲜花饼', calories: 180, protein: 3, carbs: 35, fat: 8, price: 8, healthTags: [] },
      { name: '凉拌米线', calories: 320, protein: 6, carbs: 70, fat: 5, price: 15, healthTags: ['低脂'] },
      { name: '宣威火腿', calories: 280, protein: 22, carbs: 2, fat: 20, price: 45, healthTags: ['高蛋白'] },
      { name: '普洱茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 10, healthTags: ['零卡'] }
    ],
    taste: ['咸鲜', '清淡'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '22',
    name: '东北饺子馆',
    campus: '北航校区',
    category: '中式快餐',
    avgPrice: 30,
    rating: 4.3,
    distance: 0.6,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 234,
    tags: ['一人食', '朋友聚餐', '平价'],
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=600&q=80', // Dumplings
    description: '皮薄馅大，手工现包。',
    businessHours: '10:00 - 21:30',
    location: { lat: 39.989, lng: 116.344, address: '北航南门外' },
    savingTip: '每满30个送凉菜一份。',
    recommendedDishes: [
      { name: '猪肉大葱水饺', calories: 480, protein: 20, carbs: 60, fat: 18, price: 25, healthTags: [] }
    ],
    menu: [
      { name: '猪肉大葱水饺', calories: 480, protein: 20, carbs: 60, fat: 18, price: 25, healthTags: [] },
      { name: '三鲜水饺', calories: 420, protein: 22, carbs: 55, fat: 14, price: 28, healthTags: [] },
      { name: '酸菜猪肉水饺', calories: 460, protein: 18, carbs: 58, fat: 16, price: 25, healthTags: [] },
      { name: '锅包肉', calories: 850, protein: 35, carbs: 95, fat: 42, price: 58, healthTags: [] },
      { name: '地三鲜', calories: 420, protein: 5, carbs: 45, fat: 28, price: 22, healthTags: [] },
      { name: '小鸡炖蘑菇', calories: 650, protein: 48, carbs: 15, fat: 38, price: 68, healthTags: ['高蛋白'] },
      { name: '拉皮', calories: 280, protein: 4, carbs: 65, fat: 2, price: 18, healthTags: ['低脂'] },
      { name: '酱骨架', calories: 520, protein: 42, carbs: 5, fat: 35, price: 45, healthTags: ['高蛋白'] },
      { name: '哈尔滨红肠', calories: 320, protein: 18, carbs: 5, fat: 25, price: 28, healthTags: [] },
      { name: '格瓦斯', calories: 150, protein: 0, carbs: 35, fat: 0, price: 12, healthTags: [] }
    ],
    taste: ['咸鲜'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '23',
    name: '印度咖喱屋',
    campus: '人大校区',
    category: '异域风情',
    avgPrice: 70,
    rating: 4.4,
    distance: 1.2,
    isNew: true,
    isHealthyFriendly: false,
    hasStudentDeal: false,
    yesterdayOrders: 112,
    tags: ['朋友聚餐', '重口味', '异域风情'],
    image: 'https://images.unsplash.com/photo-1585937421612-70a0f295561a?w=600&q=80', // Curry
    description: '浓郁咖喱，香脆烤饼。',
    businessHours: '11:00 - 21:30',
    location: { lat: 39.979, lng: 116.329, address: '人大东门外' },
    savingTip: '新店开业全场8.8折。',
    recommendedDishes: [
      { name: '黄油鸡咖喱', calories: 550, protein: 30, carbs: 15, fat: 42, price: 58, healthTags: [] }
    ],
    menu: [
      { name: '黄油鸡咖喱', calories: 550, protein: 30, carbs: 15, fat: 42, price: 58, healthTags: [] },
      { name: '羊肉咖喱', calories: 580, protein: 32, carbs: 12, fat: 45, price: 68, healthTags: ['高蛋白'] },
      { name: '印度烤饼(Naan)', calories: 250, protein: 8, carbs: 45, fat: 5, price: 12, healthTags: [] },
      { name: '坦都里烤鸡', calories: 380, protein: 45, carbs: 5, fat: 22, price: 52, healthTags: ['高蛋白'] },
      { name: '萨莫萨三角饺', calories: 180, protein: 4, carbs: 25, fat: 8, price: 15, healthTags: [] },
      { name: '印度拉茶', calories: 150, protein: 4, carbs: 25, fat: 5, price: 15, healthTags: [] },
      { name: '菠菜芝士咖喱', calories: 320, protein: 15, carbs: 12, fat: 22, price: 48, healthTags: [] },
      { name: '印度香饭(Biryani)', calories: 650, protein: 25, carbs: 95, fat: 22, price: 45, healthTags: [] },
      { name: '芒果拉西', calories: 220, protein: 6, carbs: 45, fat: 4, price: 22, healthTags: [] },
      { name: '扁豆汤', calories: 180, protein: 12, carbs: 28, fat: 2, price: 20, healthTags: ['低脂'] }
    ],
    taste: ['辛辣', '咸鲜'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '24',
    name: '上海生煎包',
    campus: '清华校区',
    category: '小吃',
    avgPrice: 22,
    rating: 4.5,
    distance: 0.3,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 367,
    tags: ['一人食', '图书馆速食', '平价'],
    image: 'https://images.unsplash.com/photo-1626199057193-02ec8a71246c?w=600&q=80', // Shengjianbao
    description: '底脆肉鲜，汤汁浓郁。',
    businessHours: '07:00 - 20:00',
    location: { lat: 39.996, lng: 116.326, address: '清华东门商业街' },
    savingTip: '买4个送1个。',
    recommendedDishes: [
      { name: '招牌生煎包', calories: 380, protein: 15, carbs: 40, fat: 18, price: 12, healthTags: [] }
    ],
    menu: [
      { name: '招牌生煎包', calories: 380, protein: 15, carbs: 40, fat: 18, price: 12, healthTags: [] },
      { name: '鲜肉小笼包', calories: 320, protein: 14, carbs: 35, fat: 15, price: 18, healthTags: [] },
      { name: '蟹粉小笼', calories: 350, protein: 16, carbs: 35, fat: 18, price: 32, healthTags: [] },
      { name: '上海冷面', calories: 450, protein: 10, carbs: 85, fat: 12, price: 15, healthTags: [] },
      { name: '排骨年糕', calories: 580, protein: 22, carbs: 75, fat: 22, price: 25, healthTags: [] },
      { name: '红烧肉', calories: 850, protein: 35, carbs: 15, fat: 75, price: 58, healthTags: [] },
      { name: '四喜烤麸', calories: 220, protein: 12, carbs: 18, fat: 12, price: 18, healthTags: [] },
      { name: '油爆虾', calories: 320, protein: 28, carbs: 5, fat: 22, price: 48, healthTags: ['高蛋白'] },
      { name: '酒酿圆子', calories: 280, protein: 4, carbs: 65, fat: 2, price: 12, healthTags: [] },
      { name: '咸肉菜饭', calories: 520, protein: 15, carbs: 85, fat: 15, price: 20, healthTags: [] }
    ],
    taste: ['咸鲜', '清淡'],
    cuisineType: ['饭']
  },
  {
    id: '25',
    name: '法式甜品店',
    campus: '北大校区',
    category: '甜品',
    avgPrice: 55,
    rating: 4.8,
    distance: 0.8,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: false,
    yesterdayOrders: 88,
    tags: ['约会氛围', '精致', '下午茶'],
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80', // Cake
    description: '精致甜点，浪漫午后。',
    businessHours: '10:00 - 20:00',
    location: { lat: 39.986, lng: 116.316, address: '北大未名湖畔' },
    savingTip: '生日预订蛋糕9折。',
    recommendedDishes: [
      { name: '草莓慕斯', calories: 350, protein: 5, carbs: 45, fat: 18, price: 38, healthTags: [] }
    ],
    menu: [
      { name: '草莓慕斯', calories: 350, protein: 5, carbs: 45, fat: 18, price: 38, healthTags: [] },
      { name: '经典马卡龙', calories: 120, protein: 2, carbs: 15, fat: 6, price: 15, healthTags: [] },
      { name: '法式焦糖布丁', calories: 280, protein: 4, carbs: 32, fat: 16, price: 28, healthTags: [] },
      { name: '巧克力熔岩蛋糕', calories: 450, protein: 6, carbs: 48, fat: 28, price: 42, healthTags: [] },
      { name: '歌剧院蛋糕', calories: 420, protein: 7, carbs: 45, fat: 25, price: 45, healthTags: [] },
      { name: '拿破仑酥', calories: 380, protein: 5, carbs: 42, fat: 22, price: 35, healthTags: [] },
      { name: '舒芙蕾', calories: 220, protein: 8, carbs: 25, fat: 12, price: 48, healthTags: [] },
      { name: '柠檬塔', calories: 320, protein: 4, carbs: 45, fat: 15, price: 32, healthTags: [] },
      { name: '欧蕾咖啡', calories: 180, protein: 6, carbs: 20, fat: 8, price: 32, healthTags: [] },
      { name: '大吉岭红茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 28, healthTags: ['零卡'] }
    ],
    taste: ['甜'],
    cuisineType: ['饮品']
  },
  {
    id: '26',
    name: '广式烧腊',
    campus: '北航校区',
    category: '粤菜',
    avgPrice: 38,
    rating: 4.4,
    distance: 0.4,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 156,
    tags: ['一人食', '宿舍外卖', '平价'],
    image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&q=80', // Roast duck
    description: '皮脆肉嫩，酱汁入味。',
    businessHours: '10:30 - 21:00',
    location: { lat: 39.99, lng: 116.345, address: '北航校内食堂' },
    savingTip: '学生卡消费立减2元。',
    recommendedDishes: [
      { name: '深井烧鹅饭', calories: 750, protein: 28, carbs: 65, fat: 42, price: 35, healthTags: [] }
    ],
    menu: [
      { name: '深井烧鹅饭', calories: 750, protein: 28, carbs: 65, fat: 42, price: 35, healthTags: [] },
      { name: '蜜汁叉烧饭', calories: 680, protein: 25, carbs: 70, fat: 38, price: 28, healthTags: [] },
      { name: '脆皮烧肉饭', calories: 720, protein: 24, carbs: 68, fat: 45, price: 30, healthTags: [] },
      { name: '白切鸡饭', calories: 550, protein: 32, carbs: 60, fat: 22, price: 25, healthTags: ['高蛋白'] },
      { name: '烧腊双拼饭', calories: 780, protein: 30, carbs: 75, fat: 48, price: 38, healthTags: [] },
      { name: '卤水拼盘', calories: 450, protein: 38, carbs: 5, fat: 32, price: 58, healthTags: ['高蛋白'] },
      { name: '蚝油生菜', calories: 120, protein: 2, carbs: 8, fat: 10, price: 12, healthTags: ['低脂'] },
      { name: '老火例汤', calories: 150, protein: 8, carbs: 5, fat: 12, price: 8, healthTags: [] },
      { name: '冻柠茶', calories: 180, protein: 0, carbs: 45, fat: 0, price: 12, healthTags: [] },
      { name: '红豆沙', calories: 220, protein: 6, carbs: 48, fat: 2, price: 10, healthTags: ['低脂'] }
    ],
    taste: ['咸鲜'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '27',
    name: '土耳其烤肉',
    campus: '人大校区',
    category: '异域风情',
    avgPrice: 25,
    rating: 4.2,
    distance: 0.2,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 456,
    tags: ['一人食', '图书馆速食', '快捷'],
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80', // Kebab
    description: '大口吃肉，满足感爆棚。',
    businessHours: '10:00 - 22:00',
    location: { lat: 39.98, lng: 116.33, address: '人大西门外' },
    savingTip: '加肉仅需5元。',
    recommendedDishes: [
      { name: '烤肉夹馍', calories: 580, protein: 32, carbs: 48, fat: 28, price: 18, healthTags: ['高蛋白'] }
    ],
    menu: [
      { name: '烤肉夹馍', calories: 580, protein: 32, carbs: 48, fat: 28, price: 18, healthTags: ['高蛋白'] },
      { name: '土耳其烤肉卷', calories: 520, protein: 28, carbs: 55, fat: 22, price: 22, healthTags: ['高蛋白'] },
      { name: '烤肉拼盘', calories: 850, protein: 65, carbs: 10, fat: 65, price: 45, healthTags: ['高蛋白'] },
      { name: '薯条', calories: 320, protein: 3, carbs: 40, fat: 17, price: 10, healthTags: [] },
      { name: '希腊沙拉', calories: 220, protein: 8, carbs: 12, fat: 18, price: 25, healthTags: ['低卡'] },
      { name: '鹰嘴豆泥', calories: 180, protein: 10, carbs: 25, fat: 8, price: 15, healthTags: ['优质蛋白'] },
      { name: '烤鸡翅', calories: 280, protein: 22, carbs: 5, fat: 20, price: 15, healthTags: ['高蛋白'] },
      { name: '土耳其红茶', calories: 0, protein: 0, carbs: 0, fat: 0, price: 5, healthTags: ['零卡'] },
      { name: '酸奶汁(Ayran)', calories: 120, protein: 6, carbs: 8, fat: 6, price: 8, healthTags: [] },
      { name: '巴克拉瓦', calories: 350, protein: 4, carbs: 55, fat: 15, price: 12, healthTags: [] }
    ],
    taste: ['咸鲜', '辛辣'],
    cuisineType: ['饭', '饮品']
  },
  {
    id: '28',
    name: '老成都串串香',
    campus: '清华校区',
    category: '火锅',
    avgPrice: 65,
    rating: 4.6,
    distance: 0.9,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 321,
    tags: ['朋友聚餐', '夜宵续命', '重口味'],
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=600&q=80', // Chuanchuan
    description: '麻辣鲜香，越吃越过瘾。',
    businessHours: '11:00 - 01:00',
    location: { lat: 39.997, lng: 116.327, address: '清华南门外' },
    savingTip: '签子称重，学生证8.8折。',
    recommendedDishes: [
      { name: '麻辣牛肉串', calories: 80, protein: 8, carbs: 1, fat: 5, price: 1, healthTags: [] }
    ],
    menu: [
      { name: '麻辣牛肉串', calories: 80, protein: 8, carbs: 1, fat: 5, price: 1, healthTags: [] },
      { name: '香辣鸡尖', calories: 60, protein: 6, carbs: 1, fat: 4, price: 1, healthTags: [] },
      { name: '脆爽毛肚', calories: 40, protein: 7, carbs: 1, fat: 2, price: 2, healthTags: ['低卡'] },
      { name: '小郡肝', calories: 50, protein: 8, carbs: 1, fat: 3, price: 1, healthTags: [] },
      { name: '红油抄手', calories: 380, protein: 15, carbs: 45, fat: 18, price: 15, healthTags: [] },
      { name: '冒脑花', calories: 280, protein: 12, carbs: 5, fat: 25, price: 22, healthTags: [] },
      { name: '红糖冰粉', calories: 150, protein: 1, carbs: 35, fat: 0, price: 8, healthTags: ['低脂'] },
      { name: '琅琊土豆', calories: 320, protein: 4, carbs: 45, fat: 15, price: 12, healthTags: [] },
      { name: '唯怡豆奶', calories: 180, protein: 5, carbs: 25, fat: 8, price: 6, healthTags: [] },
      { name: '成都凉面', calories: 350, protein: 8, carbs: 65, fat: 10, price: 12, healthTags: [] }
    ],
    taste: ['辛辣', '麻辣'],
    cuisineType: ['面', '饮品']
  },
  {
    id: '29',
    name: '精品湘菜',
    campus: '北大校区',
    category: '湘菜',
    avgPrice: 55,
    rating: 4.5,
    distance: 0.7,
    isNew: false,
    isHealthyFriendly: false,
    hasStudentDeal: false,
    yesterdayOrders: 198,
    tags: ['朋友聚餐', '重口味', '下饭'],
    image: 'https://images.unsplash.com/photo-1563379091339-03b21bc4a4f8?w=600&q=80', // Hunan food
    description: '香辣可口，米饭杀手。',
    businessHours: '11:00 - 22:00',
    location: { lat: 39.987, lng: 116.317, address: '北大东门外' },
    savingTip: '满100减20元。',
    recommendedDishes: [
      { name: '剁椒鱼头', calories: 450, protein: 45, carbs: 5, fat: 28, price: 68, healthTags: ['高蛋白'] }
    ],
    menu: [
      { name: '剁椒鱼头', calories: 450, protein: 45, carbs: 5, fat: 28, price: 68, healthTags: ['高蛋白'] },
      { name: '农家小炒肉', calories: 520, protein: 22, carbs: 8, fat: 45, price: 32, healthTags: [] },
      { name: '剁椒金针菇', calories: 180, protein: 4, carbs: 15, fat: 12, price: 22, healthTags: [] },
      { name: '手撕高丽菜', calories: 150, protein: 3, carbs: 10, fat: 12, price: 18, healthTags: [] },
      { name: '外婆菜炒蛋', calories: 320, protein: 15, carbs: 8, fat: 25, price: 25, healthTags: [] },
      { name: '擂辣椒皮蛋', calories: 220, protein: 12, carbs: 10, fat: 15, price: 20, healthTags: [] },
      { name: '萝卜干炒腊肉', calories: 480, protein: 18, carbs: 12, fat: 42, price: 38, healthTags: [] },
      { name: '湘西土匪鸭', calories: 650, protein: 42, carbs: 10, fat: 48, price: 58, healthTags: ['高蛋白'] },
      { name: '口味虾', calories: 380, protein: 35, carbs: 12, fat: 22, price: 98, healthTags: ['高蛋白'] },
      { name: '红薯饭', calories: 280, protein: 4, carbs: 65, fat: 1, price: 3, healthTags: [] }
    ],
    taste: ['辛辣', '咸鲜'],
    cuisineType: ['饭']
  },
  {
    id: '30',
    name: '深夜炸串',
    campus: '北航校区',
    category: '小吃',
    avgPrice: 35,
    rating: 4.3,
    distance: 0.5,
    isNew: true,
    isHealthyFriendly: false,
    hasStudentDeal: true,
    yesterdayOrders: 567,
    tags: ['夜宵续命', '宿舍外卖', '解馋'],
    image: 'https://images.unsplash.com/photo-1562607378-27b1bd99326c?w=600&q=80', // Fried skewers
    description: '万物皆可炸，深夜最香。',
    businessHours: '18:00 - 03:00',
    location: { lat: 39.991, lng: 116.346, address: '北航西门外' },
    savingTip: '满30元送炸馒头片。',
    recommendedDishes: [
      { name: '炸鸡柳', calories: 650, protein: 25, carbs: 40, fat: 45, price: 15, healthTags: [] }
    ],
    menu: [
      { name: '炸鸡柳', calories: 650, protein: 25, carbs: 40, fat: 45, price: 15, healthTags: [] },
      { name: '炸薯条', calories: 320, protein: 3, carbs: 40, fat: 17, price: 10, healthTags: [] },
      { name: '炸馒头片', calories: 280, protein: 5, carbs: 45, fat: 15, price: 5, healthTags: [] },
      { name: '炸火腿肠', calories: 220, protein: 8, carbs: 10, fat: 18, price: 3, healthTags: [] },
      { name: '炸蟹棒', calories: 120, protein: 6, carbs: 12, fat: 6, price: 3, healthTags: [] },
      { name: '炸年糕', calories: 250, protein: 2, carbs: 55, fat: 4, price: 5, healthTags: [] },
      { name: '炸平菇', calories: 180, protein: 4, carbs: 15, fat: 12, price: 8, healthTags: [] },
      { name: '炸藕片', calories: 160, protein: 3, carbs: 25, fat: 8, price: 8, healthTags: [] },
      { name: '炸鸡排', calories: 450, protein: 28, carbs: 35, fat: 28, price: 18, healthTags: ['高蛋白'] },
      { name: '冰镇可乐', calories: 150, protein: 0, carbs: 38, fat: 0, price: 5, healthTags: [] }
    ],
    taste: ['咸鲜', '辛辣'],
    cuisineType: ['饭', '饮品']
  }
];

export const MEAL_PLANS: MealPlan[] = [
  {
    day: '周一',
    meals: [
      { type: '早餐', dishName: '燕麦拿铁 + 全麦三明治', restaurantName: '图书馆咖啡吧', calories: 470, budget: 50, reason: '开启元气满满的一周，低卡饱腹感强。' },
      { type: '午餐', dishName: '香煎鸡胸肉沙拉', restaurantName: '绿野轻食社', calories: 380, budget: 38, reason: '高蛋白午餐，避免下午上课犯困。' },
      { type: '晚餐', dishName: '招牌黄焖鸡(少饭)', restaurantName: '学子居黄焖鸡', calories: 550, budget: 22, reason: '平价美味，补充体力。' }
    ]
  },
  {
    day: '周二',
    meals: [
      { type: '早餐', dishName: '全麦鸡肉三明治', restaurantName: '图书馆咖啡吧', calories: 320, budget: 22, reason: '快速便捷，适合早八人。' },
      { type: '午餐', dishName: '牛油果大虾波奇饭', restaurantName: '绿野轻食社', calories: 450, budget: 48, reason: '优质脂肪摄入，营养均衡。' },
      { type: '晚餐', dishName: '博多豚骨拉面', restaurantName: '深夜食堂拉面', calories: 850, budget: 32, reason: '辛苦一天后的奖励。' }
    ]
  }
];
